apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres
    spec:
      initContainers:
        - name: init-db
          image: postgres:14
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Set correct ownership and permissions
              chown -R postgres:postgres /var/lib/postgresql/data &&

              # Initialize the PostgreSQL data directory
              su - postgres -c "/usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/data" &&
              
              # Copy custom pg_hba.conf from the ConfigMap to the data directory
              cp /config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf &&
              
              # Set correct ownership and permissions
              chown -R postgres:postgres /var/lib/postgresql/data &&
              chmod 600 /var/lib/postgresql/data/pg_hba.conf
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql/data
            - name: pg-hba-config
              mountPath: /config

      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          resources:
            limits:
              cpu: "1"
              memory: "2Gi" # Adjust based on your requirements
            requests:
              cpu: "0.5"
              memory: "1Gi" # Adjust based on your requirements
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: pg-hba-config
          configMap:
            name: postgres-config