apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               trust
