apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-metrics
  namespace: identity
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  namespaceSelector:
    matchNames:
      - identity
  podMetricsEndpoints:
  - path: /metrics
    targetPort: 8080